version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    build:
      context: ./nginx
    restart: always
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx/matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
      - letsencrypt:/etc/letsencrypt
      - ./nginx/certbot.sh:/etc/certbot.sh
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    links:
      - app


volumes:
  db:
  matomo:
  letsencrypt:
